version: '3.5'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: "${HASURA_GRAPHQL_ADMIN_SECRET}"
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.2.1
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:${HASURA_GRAPHQL_ADMIN_SECRET}@postgres:5432/postgres'
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://hasura-backend-plus:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'false'
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ADMIN_INTERNAL_ERRORS: "true"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
  hasura-backend-plus:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '8081:3000'
    environment:
      SERVER_URL: "http://localhost:3000"
      HASURA_ENDPOINT: "http://graphql-engine:8080/v1/graphql"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      JWT_ALGORITHM: RS256
      AUTO_MIGRATE: "true"
      GOOGLE_ENABLE: "true"
      GOOGLE_CLIENT_ID: "487235771471-og6uv9lp2637ip2f3lprbocne23r8d01.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      REDIRECT_URL_SUCCESS: "https://sgdq.shaneschulte.com/"
      REDIRECT_URL_ERROR: "https://sgdq.shaneschulte.com/"
      SERVER_URL: "https://sgdq.shaneschulte.com/rest"
volumes:
  db_data:
    external:
      name: sgdq_db_data
